### PR TITLE
Add Webpack injection utility

### PR DESCRIPTION
**Pull request by amoshydra**
Include additional commit on top of #5

Features:
- Added utility function to help users to configure their Storybook's webpack config. This utility function will specifically target `vue-loader` rule for option injection.
- Added jest tests for testing utility function

Fix:
- Replace object spread operator with Object assign
- Make `extensions` optional

### CODE REVIEW

**Comment by mattrothenberg** [comment]
Hi @amoshydra, thanks for sending this along.

I'm a little confused, though.

1. Why didn't you add to the existing PR that's in the queue?
2. What problem does this solve exactly?

**Comment by amoshydra** [comment]
Hi @mattrothenberg, 

1. sorry I do not know how to add this to the existing PR. Should I make a PR to colinfindlay-nz's master branch instead?
2. This PR attempt to:
    - abstract away the detail of configuring the storybook's webpack
    - fix compatibility issue from colinfindlay-nz's PR

**Comment by mattrothenberg** [comment]
I'll play around with this this weekend to understand what changed / why.

Stay tuned.

**Comment by amoshydra** [comment]
Added additional changes to make it compatible with both
- `vue-loader` ≤ v14
- `vue-loader` v15

Essentially restores back some of the changes made by @colinfindlay-nz 
- https://github.com/mattrothenberg/vue-storybook/pull/6/commits/229928a8da7d69b633498ca22e7ce1aa42caa823
- https://github.com/mattrothenberg/vue-storybook/pull/6/commits/519bc022f00f89a29005c3a68dfd9bbc1e798974

Tested based on
- https://github.com/mattrothenberg/vue-storybook-example for `vue-loader` ≤ v14
- https://github.com/storybooks/vue-cli-plugin-storybook for `vue-loader` v15

**Comment by amoshydra** [comment]
bump

@mattrothenberg any update on this?

**Comment by mattrothenberg** [comment]
@amoshydra Last I saw was a comment on the other PR (https://github.com/mattrothenberg/vue-storybook/pull/5#issuecomment-426443061). Are you waiting on his contribution or no?

**Comment by amoshydra** [comment]
Hi @mattrothenberg,

Initially, I was expecting the conversation to be moved here.  
However, now it does become quite confusing having to reconcile comments from two different PRs on the same issue.

I would like to wait for @colinfindlay-nz's reply on #5.

So how about we:
1. Close this PR,
2. Let me open a PR on top of @colinfindlay-nz's master branch and wait for his respond over there
3. Then discuss this issue on https://github.com/mattrothenberg/vue-storybook/pull/5

**Comment by mattrothenberg** [comment]
I like that plan 😎

Thank you!

**Pull request closed without merging**
