### PR TITLE
Fixed up to work with Webpack 4, and be less fragile to configure

### PR DESCRIPTION
**Pull request by colinfindlay-nz**
Recommended setup for Webpack was super sketch, and not recommended!
No idea if this still works with Webpack 3, but I don't see why not...probably.

### CODE REVIEW

**Comment by mattrothenberg** [comment]
Hello,

Can you please elaborate on the following:

- "super sketch"
- "not recommended"
- "fragile"

Thanks!

**Comment by colinfindlay-nz** [comment]
`storybookBaseConfig.module.rules[1].options`

There is no way you can guarantee that index 1 of the webpack rules is what you expect it to be... In my case it was the css-loader....

**Comment by mattrothenberg** [comment]
Great! That's a lot more constructive than "super sketch," "not recommended," or "fragile."

Please verify that this is indeed backwards compatible with earlier versions of Webpack (e.g., 3) and we'll get it merged.

Thanks!

**Comment by colinfindlay-nz** [comment]
Sure - I will stand up a webpack 3 test case and regression test the code when I get time, as I don't have anything on hand.

**Comment by amoshydra** [comment]
I am not able to get this PR to work with `@storybook/vue` using https://github.com/mattrothenberg/vue-storybook-example as base where `@storybook/vue` make use of:
- "webpack": "^3.10.0",
- "vue-loader": "13.6.1",

### Problem
It appear that, none of the `story` block get passed into storyLoader when using
- `resourceQuery: /blockType=story/,` or
- the [instruction given by Vue Loader](https://vue-loader.vuejs.org/guide/custom-blocks.html).

Other custom block implementation doesn't seems to make use of resourceQuery too
- https://github.com/eddyerburgh/vue-test-loader/blame/263c405e/README.md#L20-L26 

I suspect vue-loader's [default documentation](https://vue-loader.vuejs.org/guide/custom-blocks.html) is targeted towards vue-loader version v15, but Storybook Vue is still using v13.


### Additional issue with backward compatibility

#### Spread syntax
Spread syntax is also not yet supported by webpack 3 (according to this [conversation](https://github.com/webpack/webpack/issues/5548#issuecomment-384477783))

https://github.com/mattrothenberg/vue-storybook/blob/e91801747026354114d8cf54e7b75e9b0f9db867/src/register-stories.js#L32-L40

#### Unspecified `extensions` crash the script
The script will crash if extensions is not defined. We could make this default to empty object `{}`

### Suggestion
https://github.com/mattrothenberg/vue-storybook/pull/6
Add a utility function to help users to configure their Storybook's webpack config. This utility function will specifically target `vue-loader` rule for option injection.

and include additional fix for webpack 3 compatibility
- Replace object spread operator with Object assign
- Make `extensions` optional

**Comment by colinfindlay-nz** [comment]
Thanks for all the feedback @amoshydra. I haven't had time to create a test project with Webpack 3 or older versions other than that which is provided by vue-cli 3.0.
I should be able to get some proper testing done next week though, and will see what I can conjure up.

**Comment by amoshydra** [comment]
Hi @colinfindlay-nz,

I have moved the suggested code change into https://github.com/colinfindlay-nz/vue-storybook/pull/1 regarding to the compatibility issue mentioned above.

To facilitate the review process, let me create a repo consisting of the 2 environments for testing this base on these 2 repo
- https://github.com/mattrothenberg/vue-storybook-example for vue-loader ≤ v14
- https://github.com/storybooks/vue-cli-plugin-storybook for vue-loader v15

I will post an update again once the test repo is up

**Comment by amoshydra** [comment]
Hi everyone,

I have created a test repo containing tests for different storybook versions using different versions of vue-storybook. Link: https://github.com/amoshydra/repro-mattrothenberg-vue-storybook-5

5 scenarios are created for each storybook versions.

0. `USE_INDEX_BASED_MUTATION` - Original approach
1. `USE_INDEX_BASED_MUTATION_V15` - Original approach tweak for storybook 4
2. `USE_RESOURCE_QUERY` - colinfindlay-nz's approach
3. `USE_INJECT_UTILITY` - amoshydra's util approach for storybook 3
4. `USE_RESOURCE_QUERY_AMOSHYDRA` - colinfindlay-nz's approach

Detailed setup guide can be found inside the Readme.

Hopefully this can help in testing the proposed PRs.

**Comment by mattrothenberg** [comment]
@amoshydra @colinfindlay-nz If either of you is interested, I took a swing at making the loader + helper script compatible with storybook projects scaffolded with Vue CLI + https://github.com/storybooks/vue-cli-plugin-storybook)

https://github.com/mattrothenberg/vue-storybook/issues/7

Let me know what you think, and whether we can work any of this feedback into that branch.

**Pull request closed without merging**
